//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace PerformanceTestTool.Properties {
    using System;
    
    
    /// <summary>
    ///   一个强类型的资源类，用于查找本地化的字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 VS 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存的 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("PerformanceTestTool.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   使用此强类型资源类，为所有资源查找
        ///   重写当前线程的 CurrentUICulture 属性。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查找类似 &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot;?&gt;
        ///&lt;tasks description=&quot;Basic Task Collection Example.&amp;#xD;&amp;#xA;&quot; connections=&quot;50&quot; timeBetweenConnections=&quot;0&quot; performanceCountersSamplingInterval=&quot;1000&quot; mode=&quot;Parallel&quot; usePooling=&quot;True&quot; minPooling=&quot;0&quot; maxPooling=&quot;100&quot;&gt;
        ///	&lt;task name=&quot;Create test database&quot; sql=&quot;use [master]&amp;#xD;&amp;#xA;&amp;#xD;&amp;#xA;if exists (select 1 from sys.databases d where d.name = &apos;TemporaryTestDatabase&apos;)&amp;#xD;&amp;#xA;begin&amp;#xD;&amp;#xA;	alter database [TemporaryTestDatabase] set single_user with rollback immediat [字符串的其余部分被截断]&quot;; 的本地化字符串。
        /// </summary>
        internal static string BasicPerformanceTest {
            get {
                return ResourceManager.GetString("BasicPerformanceTest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap bullet_wrench1 {
            get {
                object obj = ResourceManager.GetObject("bullet_wrench1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap cmd_small {
            get {
                object obj = ResourceManager.GetObject("cmd_small", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找类似于 (图标) 的 System.Drawing.Icon 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Icon cog_add {
            get {
                object obj = ResourceManager.GetObject("cog_add", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap cog_add1 {
            get {
                object obj = ResourceManager.GetObject("cog_add1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap cog_delete {
            get {
                object obj = ResourceManager.GetObject("cog_delete", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找类似于 (图标) 的 System.Drawing.Icon 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Icon cog_edit {
            get {
                object obj = ResourceManager.GetObject("cog_edit", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap cog_edit1 {
            get {
                object obj = ResourceManager.GetObject("cog_edit1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap cog_go {
            get {
                object obj = ResourceManager.GetObject("cog_go", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap cog1 {
            get {
                object obj = ResourceManager.GetObject("cog1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap cogtab {
            get {
                object obj = ResourceManager.GetObject("cogtab", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap control_pause {
            get {
                object obj = ResourceManager.GetObject("control_pause", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap control_stop {
            get {
                object obj = ResourceManager.GetObject("control_stop", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找类似 if exists (select * from sys.server_event_sessions e where e.name = &apos;{0}&apos;)
        ///begin
        ///	drop event session [{0}] on server
        ///end
        ///
        ///create event session [{0}] on server
        ///add event sqlserver.rpc_completed
        ///(
        ///	action (sqlserver.database_name)
        ///	where sqlserver.not_equal_i_sql_unicode_string ([statement], N&apos;exec sp_reset_connection&apos;)
        ///)
        ///, add event sqlserver.sql_batch_completed
        ///(
        ///	action (sqlserver.database_name)
        ///	where sqlserver.not_equal_i_sql_unicode_string (sqlserver.sql_text, N&apos;SET STATISTICS IO ON&apos;)
        ///	an [字符串的其余部分被截断]&quot;; 的本地化字符串。
        /// </summary>
        internal static string CreateEventSession {
            get {
                return ResourceManager.GetString("CreateEventSession", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 declare @TraceID int
        ///declare @rc int
        ///declare @maxfilesize bigint
        ///set @maxfilesize = 5000
        ///
        ///exec @rc = sp_trace_create @TraceID output, 2, N&apos;{0}&apos;, @maxfilesize, null
        ///select @TraceID TraceID, @rc ReturnCode
        /// 的本地化字符串。
        /// </summary>
        internal static string CreateTrace {
            get {
                return ResourceManager.GetString("CreateTrace", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap database_key_small {
            get {
                object obj = ResourceManager.GetObject("database_key_small", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找类似 &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot;?&gt;
        ///&lt;stylesheets description=&quot;Default Stylesheet Collection.&quot;&gt;
        ///	&lt;stylesheet name=&quot;Graphs&quot; description=&quot;Showing Graphs for various collected data.&quot; xsl=&quot;&amp;lt;?xml version=&apos;1.0&apos; encoding=&amp;quot;utf-8&amp;quot;?&amp;gt;&amp;#xD;&amp;#xA;&amp;#xD;&amp;#xA;&amp;lt;!-- Made with Xml Visualizer v.2 http://xmlvisualizer.codeplex.com/ --&amp;gt;&amp;#xD;&amp;#xA;&amp;#xD;&amp;#xA;&amp;lt;xsl:stylesheet version=&amp;quot;1.0&amp;quot; xmlns:xsl=&amp;quot;http://www.w3.org/1999/XSL/Transform&amp;quot;&amp;gt;&amp;#xD;&amp;#xA;&amp;#xD;&amp;#xA;	&amp;lt;xsl:template match=&amp;q [字符串的其余部分被截断]&quot;; 的本地化字符串。
        /// </summary>
        internal static string DefaultStylesheets {
            get {
                return ResourceManager.GetString("DefaultStylesheets", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap diagram_large {
            get {
                object obj = ResourceManager.GetObject("diagram_large", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap disk {
            get {
                object obj = ResourceManager.GetObject("disk", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找类似 if exists (select * from sys.server_event_sessions e where e.name = &apos;{0}&apos;)
        ///begin
        ///	drop event session [{0}] on server
        ///end
        /// 的本地化字符串。
        /// </summary>
        internal static string DropEventSession {
            get {
                return ResourceManager.GetString("DropEventSession", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap edit {
            get {
                object obj = ResourceManager.GetObject("edit", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap find_small {
            get {
                object obj = ResourceManager.GetObject("find_small", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap folder {
            get {
                object obj = ResourceManager.GetObject("folder", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap font {
            get {
                object obj = ResourceManager.GetObject("font", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找类似 select isnull(event_xml.value(&apos;(./data[@name=&quot;batch_text&quot;]/value)[1]&apos;, &apos;varchar(max)&apos;), event_xml.value(&apos;(./data[@name=&quot;statement&quot;]/value)[1]&apos;, &apos;varchar(max)&apos;)) TextData
        ///, event_xml.value(&apos;(./data[@name=&quot;logical_reads&quot;]/value)[1]&apos;, &apos;bigint&apos;) Reads
        ///, event_xml.value(&apos;(./data[@name=&quot;writes&quot;]/value)[1]&apos;, &apos;bigint&apos;) Writes
        ///, event_xml.value(&apos;(./data[@name=&quot;cpu_time&quot;]/value)[1]&apos;, &apos;bigint&apos;) CPU
        ///, event_xml.value(&apos;(./data[@name=&quot;row_count&quot;]/value)[1]&apos;, &apos;bigint&apos;) RowCounts
        ///, event_xml.value(&apos;(./data[@name=&quot;dura [字符串的其余部分被截断]&quot;; 的本地化字符串。
        /// </summary>
        internal static string GetEventSessionData {
            get {
                return ResourceManager.GetString("GetEventSessionData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 select isnull(event_xml.value(&apos;(./data[@name=&quot;batch_text&quot;]/value)[1]&apos;, &apos;varchar(max)&apos;), event_xml.value(&apos;(./data[@name=&quot;statement&quot;]/value)[1]&apos;, &apos;varchar(max)&apos;)) TextData
        ///, convert(varchar(23), dateadd(hh, datediff(hh, getutcdate(), current_timestamp), event_xml.value(&apos;(./@timestamp)&apos;, &apos;datetime2&apos;)), 21) StartTime
        ///, event_xml.value(&apos;(./action[@name=&quot;database_name&quot;]/value)[1]&apos;, &apos;varchar(128)&apos;) DatabaseName
        ///from
        ///(
        ///	select x.object_name Type, convert(xml, event_data) event_data_xml
        ///	from sys.fn_xe_file_ta [字符串的其余部分被截断]&quot;; 的本地化字符串。
        /// </summary>
        internal static string GetEventSessionRecordingData {
            get {
                return ResourceManager.GetString("GetEventSessionRecordingData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 select p.object_name ObjectName, p.counter_name CounterName, p.instance_name InstanceName, p.cntr_value Value
        ///from sys.dm_os_performance_counters p
        /// 的本地化字符串。
        /// </summary>
        internal static string GetPerformanceCounters {
            get {
                return ResourceManager.GetString("GetPerformanceCounters", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 select t.TextData, t.Reads, t.Writes, t.CPU, t.RowCounts, t.Duration / 1000 Duration, convert(varchar(23), t.StartTime, 21) StartTime
        ///from fn_trace_gettable(&apos;{0}.trc&apos;, default) t
        /// 的本地化字符串。
        /// </summary>
        internal static string GetTraceData {
            get {
                return ResourceManager.GetString("GetTraceData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 select t.TextData, convert(varchar(23), t.StartTime, 21) StartTime, t.DatabaseName
        ///from fn_trace_gettable(&apos;{0}.trc&apos;, default) t
        /// 的本地化字符串。
        /// </summary>
        internal static string GetTraceRecordingData {
            get {
                return ResourceManager.GetString("GetTraceRecordingData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap help1 {
            get {
                object obj = ResourceManager.GetObject("help1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Byte[] 类型的本地化资源。
        /// </summary>
        internal static byte[] ICSharpCode_SharpZipLib {
            get {
                object obj = ResourceManager.GetObject("ICSharpCode_SharpZipLib", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Byte[] 类型的本地化资源。
        /// </summary>
        internal static byte[] ICSharpCode_TextEditor {
            get {
                object obj = ResourceManager.GetObject("ICSharpCode_TextEditor", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   查找类似 &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot;?&gt;
        ///&lt;tasks description=&quot;IO Performance Test.&amp;#xD;&amp;#xA;When finished, apply the Stylesheet &amp;quot;IO Performance Statistics&amp;quot; from the default Stylesheet Collection.&amp;#xD;&amp;#xA;&quot; connections=&quot;5&quot; timeBetweenConnections=&quot;0&quot; performanceCountersSamplingInterval=&quot;0&quot; mode=&quot;Serial&quot; usePooling=&quot;True&quot; minPooling=&quot;0&quot; maxPooling=&quot;100&quot;&gt;
        ///	&lt;task name=&quot;Create test database&quot; sql=&quot;use [master]&amp;#xD;&amp;#xA;&amp;#xD;&amp;#xA;if exists (select 1 from sys.databases d where d.name = &apos;TemporaryTestDataba [字符串的其余部分被截断]&quot;; 的本地化字符串。
        /// </summary>
        internal static string IOPerformanceTest {
            get {
                return ResourceManager.GetString("IOPerformanceTest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot;?&gt;
        ///&lt;tasks description=&quot;Step 1 will run for 30 minutes. While running, Performance Counters will be collected every minute.&amp;#xD;&amp;#xA;When finished, apply the Stylesheet &amp;quot;User Connections&amp;quot; from the default Stylesheet Collection.&quot; connections=&quot;1&quot; timeBetweenConnections=&quot;0&quot; performanceCountersSamplingInterval=&quot;60000&quot; mode=&quot;Parallel&quot; usePooling=&quot;True&quot; minPooling=&quot;0&quot; maxPooling=&quot;100&quot;&gt;
        ///	&lt;task name=&quot;Collect Performance Counters&quot; sql=&quot;waitfor delay &apos;00:30:00&apos;&amp;#xD;&amp;#xA; [字符串的其余部分被截断]&quot;; 的本地化字符串。
        /// </summary>
        internal static string MeasureConnectionsOverTime {
            get {
                return ResourceManager.GetString("MeasureConnectionsOverTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似于 (图标) 的 System.Drawing.Icon 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Icon page_add {
            get {
                object obj = ResourceManager.GetObject("page_add", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap page_add_small {
            get {
                object obj = ResourceManager.GetObject("page_add_small", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap page_delete_small {
            get {
                object obj = ResourceManager.GetObject("page_delete_small", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找类似于 (图标) 的 System.Drawing.Icon 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Icon page_edit {
            get {
                object obj = ResourceManager.GetObject("page_edit", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap page_edit_small {
            get {
                object obj = ResourceManager.GetObject("page_edit_small", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap page_small {
            get {
                object obj = ResourceManager.GetObject("page_small", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找类似 &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot;?&gt;
        ///&lt;tasks description=&quot;See description in Step 1 of the &amp;quot;Normal&amp;quot; Task Type.&amp;#xD;&amp;#xA;When finished, apply the Stylesheet &amp;quot;Stylesheet for Parameter Example 1&amp;quot; from the default Stylesheet Collection.&quot; connections=&quot;10&quot; timeBetweenConnections=&quot;0&quot; performanceCountersSamplingInterval=&quot;0&quot; mode=&quot;Parallel&quot; usePooling=&quot;True&quot; minPooling=&quot;0&quot; maxPooling=&quot;100&quot;&gt;
        ///	&lt;task name=&quot;Create test database&quot; sql=&quot;use [master]&amp;#xD;&amp;#xA;&amp;#xD;&amp;#xA;if exists (select 1 from sys.dat [字符串的其余部分被截断]&quot;; 的本地化字符串。
        /// </summary>
        internal static string ParametersExample1 {
            get {
                return ResourceManager.GetString("ParametersExample1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot;?&gt;
        ///&lt;tasks description=&quot;Shows an example of how to get uniform distributed values based on parameters.&quot; connections=&quot;50&quot; timeBetweenConnections=&quot;0&quot; performanceCountersSamplingInterval=&quot;0&quot; mode=&quot;Parallel&quot; usePooling=&quot;True&quot; minPooling=&quot;0&quot; maxPooling=&quot;100&quot;&gt;
        ///	&lt;task name=&quot;Create test database&quot; sql=&quot;use [master]&amp;#xD;&amp;#xA;&amp;#xD;&amp;#xA;if exists (select 1 from sys.databases d where d.name = &apos;TemporaryTestDatabase&apos;)&amp;#xD;&amp;#xA;begin&amp;#xD;&amp;#xA;	alter database [TemporaryTestDatabase] set [字符串的其余部分被截断]&quot;; 的本地化字符串。
        /// </summary>
        internal static string ParametersExample2 {
            get {
                return ResourceManager.GetString("ParametersExample2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 &lt;?xml version=&quot;1.0&quot;?&gt;
        ///&lt;xsd:schema attributeFormDefault=&quot;qualified&quot; elementFormDefault=&quot;qualified&quot; xmlns:xsd=&quot;http://www.w3.org/2001/XMLSchema&quot;&gt;
        ///
        ///	&lt;xsd:simpleType name=&quot;dateTime&quot;&gt;
        ///		&lt;xsd:restriction base=&quot;xsd:string&quot;&gt;
        ///			&lt;xsd:maxLength value=&quot;23&quot; /&gt;
        ///		&lt;/xsd:restriction&gt;
        ///	&lt;/xsd:simpleType&gt;
        ///	&lt;xsd:simpleType name=&quot;str50&quot;&gt;
        ///		&lt;xsd:restriction base=&quot;xsd:string&quot;&gt;
        ///			&lt;xsd:maxLength value=&quot;50&quot; /&gt;
        ///		&lt;/xsd:restriction&gt;
        ///	&lt;/xsd:simpleType&gt;
        ///	&lt;xsd:simpleType name=&quot;str128&quot;&gt;
        ///		&lt;xsd:restriction base=&quot;xsd:string&quot; [字符串的其余部分被截断]&quot;; 的本地化字符串。
        /// </summary>
        internal static string PerformanceTestToolXmlResult {
            get {
                return ResourceManager.GetString("PerformanceTestToolXmlResult", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap Profiler {
            get {
                object obj = ResourceManager.GetObject("Profiler", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap programicon_small {
            get {
                object obj = ResourceManager.GetObject("programicon_small", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找类似 declare @ram sql_variant
        ///select @ram = cfg.value
        ///from sys.configurations cfg
        ///where cfg.name = &apos;max server memory (MB)&apos;
        ///
        ///select i.cpu_count &apos;Logical CPU Count&apos;, i.hyperthread_ratio &apos;Hyperthread Ratio&apos;, i.cpu_count / i.hyperthread_ratio &apos;Physical CPU Count&apos;, i.{0} &apos;Physical Memory (MB)&apos;, @@version version, @ram ram
        ///from sys.dm_os_sys_info i
        /// 的本地化字符串。
        /// </summary>
        internal static string SqlServerInfo {
            get {
                return ResourceManager.GetString("SqlServerInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 alter event session [{0}] on server state = start
        /// 的本地化字符串。
        /// </summary>
        internal static string StartEventSession {
            get {
                return ResourceManager.GetString("StartEventSession", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 {1}
        ///alter event session [{0}] on server state = start
        /// 的本地化字符串。
        /// </summary>
        internal static string StartEventSessionRecording {
            get {
                return ResourceManager.GetString("StartEventSessionRecording", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 declare @on bit
        ///set @on = 1
        ///
        ///-- SQL:BatchCompleted
        ///exec sp_trace_setevent {0}, 12, 1, @on	-- TextData
        ///exec sp_trace_setevent {0}, 12, 14, @on	-- StartTime
        ///exec sp_trace_setevent {0}, 12, 16, @on	-- Reads
        ///exec sp_trace_setevent {0}, 12, 17, @on	-- Writes
        ///exec sp_trace_setevent {0}, 12, 18, @on	-- CPU
        ///exec sp_trace_setevent {0}, 12, 48, @on	-- RowCounts
        ///exec sp_trace_setevent {0}, 12, 13, @on	-- Duration
        ///
        ///exec sp_trace_setstatus {0}, 1
        /// 的本地化字符串。
        /// </summary>
        internal static string StartTrace {
            get {
                return ResourceManager.GetString("StartTrace", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 {1}
        ///declare @on bit
        ///set @on = 1
        ///
        ///-- SQL:BatchCompleted
        ///exec sp_trace_setevent {0}, 12, 1, @on	-- TextData
        ///exec sp_trace_setevent {0}, 12, 14, @on	-- StartTime
        ///exec sp_trace_setevent {0}, 12, 35, @on	-- DatabaseName
        ///
        ///-- RPC:Completed
        ///exec sp_trace_setevent {0}, 10, 1, @on	-- TextData
        ///exec sp_trace_setevent {0}, 10, 14, @on	-- StartTime
        ///exec sp_trace_setevent {0}, 10, 35, @on	-- DatabaseName
        ///
        ///exec sp_trace_setfilter {0}, 1, 0, 7, N&apos;exec sp[_]reset[_]connection&apos;
        ///exec sp_trace_setfilter {0}, 1, 0 [字符串的其余部分被截断]&quot;; 的本地化字符串。
        /// </summary>
        internal static string StartTraceRecording {
            get {
                return ResourceManager.GetString("StartTraceRecording", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap stop_small {
            get {
                object obj = ResourceManager.GetObject("stop_small", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找类似 if exists (select * from ::fn_trace_getinfo(0) where left(convert(nvarchar(245), value), len(&apos;{0}&apos;)) = &apos;{0}&apos;)
        ///begin
        ///	declare @TraceID int
        ///
        ///	select @TraceID = traceid
        ///	from ::fn_trace_getinfo(0)
        ///	where left(convert(nvarchar(245), value), len(&apos;{0}&apos;)) = &apos;{0}&apos;
        ///
        ///	exec sp_trace_setstatus @TraceID, 0 -- stop trace
        ///	exec sp_trace_setstatus @TraceID, 2 -- delete trace
        ///end
        /// 的本地化字符串。
        /// </summary>
        internal static string StopDeleteTrace {
            get {
                return ResourceManager.GetString("StopDeleteTrace", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 declare @IsRunning bit
        ///
        ///select @IsRunning = t.IsRunning
        ///from
        ///(
        ///	select case
        ///		when r.create_time is null then 0 else 1
        ///	end IsRunning
        ///	from sys.server_event_sessions s
        ///	left outer join sys.dm_xe_sessions r on r.name = s.name
        ///	where s.name = &apos;{0}&apos;
        ///) t
        ///
        ///if @IsRunning = 1
        ///begin
        ///	alter event session [{0}] on server state = stop
        ///end
        /// 的本地化字符串。
        /// </summary>
        internal static string StopEventSession {
            get {
                return ResourceManager.GetString("StopEventSession", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找 System.Byte[] 类型的本地化资源。
        /// </summary>
        internal static byte[] TabControlEX {
            get {
                object obj = ResourceManager.GetObject("TabControlEX", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap update {
            get {
                object obj = ResourceManager.GetObject("update", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
    }
}
